<html style="font-family: Consolas, monospace;">
    <head>
        <title>lab01-test</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    </head>
    <body>
        <form action="/api/feedbacks" method="POST">
            <div>
                <input type="text" name="name" placeholder="Name"/>
            </div>
            <div>
                <input type="email" name="email" placeholder="E-Mail"/>
            </div>
            <div>
                <input type="text" name="phone" placeholder="Phone"/>
            </div>
            <div>
                <textarea name="message" placeholder="Message"></textarea>
            </div>
            <div>
                <button type="submit">Submit</button>
            </div>
        </form>
    </body>
</html>
